
public class Countries
{
	String[] laender = {
			"Afghanistan",
			"Ägypten",
			"Albanien",
			"Algerien",
			"Andorra",
			"Angola",
			"Antigua",
			"Argentinien",
			"Armenien",
			"Aserbaidschan",
			"Äthiopien",
			"Australien",
			"Bahamas",
			"Bahrain",
			"Bangladesh",
			"Barbados",
			"Belarus",
			"Belgien",
			"Belize",
			"Benin",
			"Bhutan",
			"Bolivien",
			"Bosnien",
			"Botswana",
			"Brasilien",
			"Brunei",
			"Bulgarien",
			"Burkina Faso",
			"Burundi",
			"China",
			"Costa Rica",
			"Dänemark",
			"Deutschland",
			"Dominica",
			"Dominikanische Republik",
			"Dschibuti",
			"Ecuador",
			"Elfenbeinküste",
			"El Salvador",
			"England/[[ UK/[[ Großbritannien",
			"Eritrea",
			"Estland",
			"Fidschi",
			"Finnland",
			"Frankreich",
			"Gabon",
			"Gambia",
			"Georgien",
			"Ghana",
			"Grenada",
			"Griechenland",
			"Guatemala",
			"Guinea",
			"Guinea",
			"Guinea-Bissau",
			"Guyana",
			"Haiti",
			"Holland",
			"Honduras",
			"Indien",
			"Indonesien",
			"Irak",
			"Iran",
			"Irland",
			"Island",
			"Israel",
			"Italien",
			"Jamaika",
			"Japan",
			"Jordanien",
			"Kambodscha",
			"Kamerun",
			"Kanada",
			"Kanada",
			"Kap Verde",
			"Kasachstan",
			"Kenia",
			"Kirgisistan",
			"Kiribati",
			"Kolumbien",
			"Kolumbien",
			"Komoren",
			"Kongo",
			"Kosovo",
			"Kroatien",
			"Kuba",
			"Kuwait",
			"Laos",
			"Lesotho",
			"Libanon",
			"Liberia",
			"Libyen",
			"Liechtenstein",
			"Liechtenstein",
			"Litauen",
			"Litauen",
			"Lithuania",
			"Luxembourg",
			"Lybien",
			"Madagaskar",
			"Malawi",
			"Malaysia",
			"Malediven",
			"Mali",
			"Malta",
			"Marokko",
			"Marshallinseln",
			"Mauritanien",
			"Mauritius",
			"Mazedonien",
			"Mexiko",
			"Mikronesien",
			"Moldawien",
			"Monaco",
			"Mongolei",
			"Montenegro",
			"Mosambik",
			"Myanmar",
			"Namibia",
			"Nauru",
			"Nepal",
			"Neuseeland",
			"Nicaragua",
			"Niger",
			"Nigeria",
			"Nordkorea",
			"Norwegen",
			"Oman",
			"Österreich",
			"Osttimor",
			"Pakistan",
			"Palau",
			"Panama",
			"Papua Neu-Guinea",
			"Paraguay",
			"Peru",
			"Philippinen",
			"Polen",
			"Portugal",
			"Puerto Rico",
			"Qatar",
			"Ruanda",
			"Rumänien",
			"Russland",
			"Saint Vincent und die Grenadinen",
			"Sambia",
			"Samoa",
			"San Marino",
			"Saudi Arabien",
			"Schweden",
			"Schweiz",
			"Senegal",
			"Serbien",
			"Seychellen",
			"Sierra Leone",
			"Singapur",
			"Slowakei",
			"Slowakei",
			"Slowenien",
			"Solomon Islands",
			"Somalia",
			"Spanien",
			"Sri Lanka",
			"St Kitts & Nevis",
			"St Lucia",
			"Südafrika",
			"Sudan",
			"Südkorea",
			"Surinam",
			"Swaziland",
			"Syrien",
			"Tadschikistan",
			"Taiwan",
			"Tansania",
			"Thailand",
			"Togo",
			"Tonga",
			"Trinidad & Tobago",
			"Tschad",
			"Tschechien",
			"Tunesien",
			"Türkei",
			"Türkei",
			"Turkmenistan",
			"Tuvalu",
			"Uganda",
			"Ukraine",
			"Ungarn",
			"Ungarn",
			"Uruguay",
			"USA",
			"Usbekistan",
			"Vanuatu",
			"Vatikan",
			"Venezuela",
			"Vereinigte Arabische Emirate",
			"Vietnam",
			"Yemen",
			"Zimbabwe",
			"Zypern"};
	
	
	public String[] getLaender()
	{
		return laender;
	}
}
